### ISSUE TITLE
Warriors Berserk breaks combo

### ISSUE THREAD

**Issue by Codemned** [Nik-Potokar/MyDalamudPlugins#1]
The storms path combo gets replaced with upheaval if berserk is on cooldown regardless if other features/combos are toggled off.

**Comment by Codemned** [comment]
It works as intended in level 70+ content when Inner release is unlocked but if your synced 69 and below it will always replace the main combo with upheaval when Berserk goes on cooldown.

**Comment by Nik-Potokar** [comment]
Should be fixed (Repo was updated to 1.4.6)
Please let me know if you come across any more issues

**Comment by Codemned** [comment]
Yes everything seems to be working as intended, Thank you!
