### ISSUE TITLE
PLD Goring Blade in Royal Authority Combo issue.

### ISSUE THREAD

**Issue by HallwayRaptor** [Nik-Potokar/MyDalamudPlugins#12]
As it stands, the Royal authority combo feature will use Goring Blade if the debuff isn't on the target or if the debuff will expire soon. However it's often the case that you don't want to use Goring Blade (such as if the target will die soon). Is it possible to get a separate check box for this feature instead of being baked into the Royal Authority combo?

**Comment by Trilkin** [comment]
More importantly: Goring Blade and the Blade of Valor DoT overwrite each other. The new opener and loop will have you go through the Royal Authority combo as filler while the BoV DoT is running, so the Goring Blade feature as is will actually be a large DPS loss.
