### ISSUE TITLE
[PLD] Requiescat Feature Update

### ISSUE THREAD

**Issue by Trilkin** [Nik-Potokar/MyDalamudPlugins#14]
In its current state, this actually is nearly useless due to Req. showing up early in our rotations now. You may want to make a check that Fight or Flight is not up as well so it doesn't get wasted.

**Comment by Codemned** [comment]
How would it get wasted?
You have to manually use Requiescat for it to replace your main combo.

**Comment by Nik-Potokar** [comment]
So as off 1.5.16 i have reverted the feature that was previously used before Endwalker aka is currently causing issues since skill changes
.
 For now everything should be back to basic features until i get a better understanding of how its the new PLD stuff supposed to work. 
 
 If you can could you please explain in detail how you want the new features to work ether here or if you want do DM me on discord Aki#9251
 
 Thanks and sorry <3

**Comment by Trilkin** [comment]
> How would it get wasted? You have to manually use Requiescat for it to replace your main combo.

It'd be wasted because you Req before/with your first Royal Authority now. If Royal Authority gets replaced by Holy Spirit, it would break the entire rotation.

**Comment by Codemned** [comment]
Then the feature is useless and you shouldn't use it.

**Comment by Trilkin** [comment]
> 

...Yes, and thus the idea is to give feedback and help improve it...?

**Comment by Codemned** [comment]
Ok i get it you want 
"if" buff "Fight or Flight" is present, disable requiescat feature
"if" buff "Fight or flight" is NOT present enable requiescat feature

Slice and dice is a wow thing sorry

**Comment by Codemned** [comment]
Two things we would like to change the above Requiescat feature and Goring Blade should never replace a Blade of Valor debuff on the enemy when doing the main combo

The main combo currently works like this: Fast Blade -> Riot Blade -> "If" goring DoT not present on target OR debuff duration is less than 5 seconds use Goring blade, if Goring blade debuff IS present on target and has a duration greater than 5 seconds use Royal Authority.

We would like this changed to also consider if Blade of Valor is present and has a duration greater than 5 seconds so it doesn't get overwritten by Goring Blade. These DoTs do not stack.

**Comment by Trilkin** [comment]
> Ok i get it you want "if" buff "Slice and dice" is present, disable requiescat feature "if" buff "slice and dice" is NOT present enable requiescat feature

To fix the entire thing:

If FoF >=2s then do not replace with magic combo.
If FoF >=2s and Goring Blade <=3s then replace RA with Goring Blade.

Provided you're weaving FoF and Req correctly, that will basically make the ST button a near brainless single button spam. You will need to adjust where you're weaving based on ping and GCD, but it will take care of the DoT logic.

**Comment by Nik-Potokar** [comment]
There will be reworked version up today so please check it out and let me know of any improvements
