### ISSUE TITLE
[WAR] Orogeny feature like upheaval 

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/MyDalamudPlugins#15]
Having an Orogeny feature, that would work just like the Upheaval one, but with the AOE combo would be wonderous, thanks.

**Comment by Nik-Potokar** [comment]
Will be added shorty (Currently a little behind fixing stuff)

Thanks <3

**Comment by Nik-Potokar** [comment]
Added with 1.6.0 update 
Check and let me know

**Comment by sauronshotdogs** [comment]
Again, thanks a bunch!

It works very well, but it seems to add it as though it was a GCD, and not an oGCD like the Upheaval feature. When I am using the AOE button, it seems to show up at the end of the rotation, and not as soon as it's available, as with Upheaval.

**Comment by sauronshotdogs** [comment]
After some testing, it seems like it does work like the Upheaval feature, although It will prioritise combo actions, before using Orogeny. If i do sing main combo, it will show up as soon as it's available, but if I use the AOE, it will prioritise finishing the combo, before showing Orogeny

**Comment by Codemned** [comment]
I think thats intended so it doesn't get wasted before mobs even have a chance to gather up, If you've already been aoeing for a while it might make sense to fire it off asap but thats just my take on it.

**Comment by sauronshotdogs** [comment]
While true, the purpose of putting in an oGCD in the main aoe rot, or any rotation for that matter, is for it to fire up as soon as it's available, so you can get it on CD.

It works well enough for me though. I'd be happy with either.

**Comment by Nik-Potokar** [comment]
**1.6.3 update**

Its intended to pop-up as right after Mythril Tempest while MT is on CD(Gcd)

I've updated it a bit so it should work a bit better (but since im unable to test it myself it wont be perfect yet)

**Comment by sauronshotdogs** [comment]
Works just as described. Might be showing up faster, but that might also be placebo. 

Shows up if I do a single ability from single target combo. Same vice versa
