### ISSUE TITLE
Reaper Death's design main combo

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/MyDalamudPlugins#16]
Is it possible to add shadow of death to slice combo, and shorl of death to scythe combo, so it works like warrior AIO storms path/eye, meaning once buff/debuff gets low, it gets added to combo again.

**Comment by Codemned** [comment]
That would be amazing!

**Comment by Nik-Potokar** [comment]
Will be added shortly

**Comment by sauronshotdogs** [comment]
I guess it would be more like with DRK, but you get the point. Thanks!

**Comment by Nik-Potokar** [comment]
Added both Slice and Scythe AoE versions with 1.6.0 update

Please let me know what you think or if its fine like it is now

**Comment by sauronshotdogs** [comment]
Works perfectly, thanks a lot!

EDIT It doesn't seem to register deaths design on hunt mobs, thereby preventing the combo from even starting. I have tried disabling other's debuffs, but that doesn't work

**Comment by Codemned** [comment]
Could you try limiting status effects with https://github.com/Caraxi/SimpleTweaksPlugin  (This is an official Dalamud plugin it's in the plugins list)

Configuration - UI Tweaks - Limit target status effects

And see if that solves the issue?

**Comment by sauronshotdogs** [comment]
I will try, thanks

Should the limit be less than the default 30 set by the plugin?

**Comment by Codemned** [comment]
Don't know i've never had to resort to this so trial and error is the way to go, either start high or low and work it out from there.

I would set it to 10 and go from there, it's not like you need to see others debuffs on the enemy.

**Comment by sauronshotdogs** [comment]
Even set to 1, it still occurs. Only happens with EW hunts though

**Comment by Codemned** [comment]
Strange I'll pass it along and see what can be done, it's most likely an issue with dalamud itself since it handles all this stuff.

**Comment by sauronshotdogs** [comment]
Since It only happens with the new hunts, I would assume so. I haven't tested them in the new trials or raids yet, but will report back when I have. Ofc keeping spoilers in mind and all.

**Comment by Nik-Potokar** [comment]
Can you tell me on which Hunt mob did it happen?

Cause i've just tried it on Thavnair Hunt Mob and the combo did work as long as i didn't MISS the attack (since my reaper is still 70 so most of my attacks will miss and if you miss the attack combo wont work until you actually hit the mob and the hit registers )

Edit:
There was an Dalamud update for me in the morning unless that fixed it maybe

**Comment by sauronshotdogs** [comment]
It has happened on more than 5, spread on several areas. I have, however, not restarted the game for at least 6 hrs. I will restart and report back. My reaper is 90, and so should not miss 10 attacks in a row.

EDIT:
Can confirm it works now. Must have been dalamud, as another plugin which affected status effects, has also started working now.

**Comment by sauronshotdogs** [comment]
Unrelated, but are you working on RDM, or should i make a ticket on my issues?

**Comment by Nik-Potokar** [comment]
I'm glad it got fixed quickly

Open another issue please and il take a look since i haven't touched it at all since EW release
