### ISSUE TITLE
RDM new abilities lockout

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/MyDalamudPlugins#18]
After unlocking Veraero III and Verthunder III at 82, the main combo will randomly grey out normal Veraero and Verthunder. Putting in Veraero III and Verthunder III in their place will not make them work with the combo.

Basically, both got upgraded versions, and it would be nice if they worked with the combo. The abilities automatically turn into their old versions, upon being level scaled.

**Comment by Nik-Potokar** [comment]
I've added the new aero and thunder skill id's and also added a level check so now they should function correctly when 82 or above. ( Please test this for me since my RDM is still only 80)

And fixed the oGCD feature

Please update to 1.6.1 and let me know if its fixed or still broken ^^

**Comment by sauronshotdogs** [comment]
Veraero III works, but Verthunder III doesn't trigger. Have tried putting Verthunder and Verthunder III in hotbar, but they don;t change. Putting Verfire down, changes it to Verthunder but not Verthunder III. 

Thanks for making this fork, and for working so fast!

wouldn't this be covered in the main mod though? Maybe they're just busy playing the msq

**Comment by Nik-Potokar** [comment]
I forgot to add Verthunder3 lmao 

Fix should be up now

Edit: I think that they just didn't have the time to add it yet but its a simple fix

Please test and let me know ^^

**Comment by sauronshotdogs** [comment]
All appears in working order now - oGCD feature also appears to work as it should now. Thanks for the speedy fix!

**Comment by Nik-Potokar** [comment]
Just let me know if anything else needs be fixed or added and il try to add/fix asap ^^
