### ISSUE TITLE
[RPR] Whorl of death level sync check

### ISSUE THREAD

**Issue by rushtothesun** [Nik-Potokar/MyDalamudPlugins#19]
Hi, if you're below level 35 (leveling roulette) then you can't use the AoE move with the Whorl of death combo. 

`WhorlOfDeath = 35,` in the Levels section and    `&& level >= RPR.Levels.WhorlOfDeath`  at the end of line 139 fixes it for me, or however you would like to do it.

**Comment by Iaotle** [comment]
fixed
