### ISSUE TITLE
Add RDM Resolution to Redoublement Combo Plus

### ISSUE THREAD

**Issue by hokeenthong** [Nik-Potokar/MyDalamudPlugins#21]
Hi,

First of all, I wish to express my greatest appreciation to your work here. Greatly improved my enjoyment of the game. Thank you.

I am posting a suggestion as I cannot find a place to post in your suggested link. My fault here because this is not an issue.

I was wondering if you can add rdm's new skill (Resolution) to redoublement combo plus.

Thanks again for the wonderful job you are doing.

**Comment by Nik-Potokar** [comment]
Sorry for late reply I will add it asap when I get home

**Comment by hokeenthong** [comment]
Thank you.

**Comment by Nik-Potokar** [comment]
Added it both to the melee and into jolt combo 

Please let me know if there are any issues.

1.6.13 should be live

**Comment by sauronshotdogs** [comment]
Doesn't show up in the RDM section

**Comment by Nik-Potokar** [comment]
Its already included in the plus combo unless you want it to be a separate option?

**Comment by sauronshotdogs** [comment]
I don't have it unlocked yet, but should be 90 after today's roulettes

**Comment by sauronshotdogs** [comment]
Reading the tooltip on Resolution, I don't see how it can even be added to a combo, as it isn't allowed manually on the hotbar. Seems like one of the built-in combos they added in EW.

**Comment by Nik-Potokar** [comment]
Yeah it wont show up unless you are lvl 90

The skill cant be assigned to a hotbar by default but with the addon it can

**Comment by sauronshotdogs** [comment]
Ill let you know when I have it unlocked, but if it's not too much work making it a different option, that would be nice. Customization is always great

**Comment by Nik-Potokar** [comment]
Will add it as option feature

**Comment by sauronshotdogs** [comment]
Just to update, I tried it out, and it works great.
