### ISSUE TITLE
[MCH] Feature: Combine Heatblast and Gauss/Ricochet when Hypercharge is active

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/MyDalamudPlugins#22]
Would like to see this as a feature, but don't know if it's possible, as it should always prioritize Heat blast, before the oGCD.

So spamming the button would result in 
Heatblast
Gauss
Ricochet
Repeat.

I know this is reducing the burst down to 1 button, but it would be awesome to see if it it's possible, and also make it easier to play on non-perfect connections.

**Comment by Iaotle** [comment]
added to testing, can try it if you want

**Comment by sauronshotdogs** [comment]
How do I access testing?

**Comment by sauronshotdogs** [comment]
Forgot to add. Wildfire needs to be in there too, and have higher prio than ricochet and gauss, but lower than hypercharge

**Comment by sauronshotdogs** [comment]
Have tried it out, and it still seems wonky.

Normally the rotation goes:

Hypercharge *this activates burst oGCD phase
Heat blast *gcd
Wildfire "dot ogcd
Heat blast *gcd
ricochet/gauss "ogcd
Heat blast *gcd
ricochet/gauss "ogcd
Heat blast *gcd
ricochet/gauss "ogcd
Heat blast *gcd
ricochet/gauss "ogcd

This thing lasting 8 seconds in total, and getting off 8 heat blasts.
You already have a feature that replaces Hypercharge with Heat blast once overheated, so this would just have to prio Heat blast when up, and then wildfire as 2nd prio, and ricochet/gauss as 3rd. These are very tight windows, so miight not be possible. 

Currently Ricochet and Gauss does now show up, unless I press it manually once, then it alternates Heat blast and ogcd. 

I am not sure what the newly added Head Blast feature does.

**Comment by Codemned** [comment]
I have fixed and improved this option wait for new release later today.

**Comment by sauronshotdogs** [comment]
Great! The #54 Heat blast feature serves no purpose, as you wouldn't want, nor be able to activate it inside your main combo. I think that may have been a miscommunication on my part.

**Comment by Codemned** [comment]
#54 on either the release or the development version has nothing to do with heat blast...???
Could you try to make an effort to be more descriptive? I'd like to help you but "serves no purpose" without giving an explanation as to why it serves no purpose doesn't give me anything to work with.

**Comment by sauronshotdogs** [comment]
I am sorry, I mistyped, I meant #57 Heat Blast Feature. I am terribly sorry.

Ill try to explain how heatblast works, and why you would not want it in your main combo (heated split shot, slug shot, clean shot etc.)

For heatblast to work, you must be Overheated, which is granted buy Hypercharge. The main hypercharge, heatblast combo is described above. Putting Heatblast into your main combo, would serve no purpose, and wouldn't be possible, unless you were Overheated, in which case, you'd be firing Heatblast and oGCDs only.  

I think the main cause for confusion is me writing the wrong number, and mistakenly not specifying that Heat blast needed to be included in the originally mentioned hypercharge 1 button combo.

**Comment by Codemned** [comment]
Have you tried the dev build?
#57 is an optional combo that I removed and then put back in because another dev actually used it, still completely optional you shouldn't enable every option in the lists they are situational/personal and conflict with eachother.

As for the Combo you want is a single button for Hypercharge, Wildfire, Heat Blast, Gauss and Ricochet. That's #56 in the dev build but I was told it wasn't cycling through the skills fast enough so an optimization is being looked for.

**Comment by sauronshotdogs** [comment]
I'm not sure how to access the dev build, sorry.

**Comment by Codemned** [comment]
It's fine I think I figured out what the problem with the current iteration of one button lazy heat blast.

It's double weaving rico/gauss and clipping Heatblast messing up the damage, I'll try and fix that.

All the information of how to load a dev build can be found at https://goatcorp.github.io/faq/development

**Comment by sauronshotdogs** [comment]
If you're talking about enabling the testing builds in dalamud, I have enabled that.

**Comment by Codemned** [comment]
From https://goatcorp.github.io/faq/development
"Q: How do I hot-reload my plugin?

As of API 4/Dalamud 6, hot-reloading is part of Dalamud. To use it, go to Dalamud Settings > Experimental > Dev Plugin Locations, and then add either the folder that your plugin is in or the plugin itself. If you add a folder, Dalamud will attempt to load all DLLs within the folder."

**Comment by Codemned** [comment]
Here I compiled my latest build for you: https://cdn.discordapp.com/attachments/918631201005240320/920232447080300594/devbuild.rar

**Comment by Codemned** [comment]
How many Heat Blasts/gauss/ricochet is it supposed to do during the 8 second hypercharge window?

**Comment by sauronshotdogs** [comment]
Should be 5x HeatBlast, with Wildfire cast beforehand, to maximise on dmg. A total of 5 casts can be fit into the Hypercharge window.

Gauss and ricochet are oGCD, and therefore don't "take up space" in the cast window, so to speak. THey're cast in between every Heatblast

**Comment by sauronshotdogs** [comment]
The devbuild is giving me an error when trying to load it.

**Comment by Codemned** [comment]
Did you put it in your dev folder?
Do you cast 1 gauss and 1 ricochet for every heat blast?

**Comment by sauronshotdogs** [comment]
I just loaded the devbuild folder. This has worked for previous builds of this.

**Comment by Codemned** [comment]
Yeah just stickit in there and you'll get https://cdn.discordapp.com/attachments/918631201005240320/920240130508349440/devbuild.png

**Comment by sauronshotdogs** [comment]
![image](https://user-images.githubusercontent.com/95890035/145967548-5044f62f-120e-4123-985e-663b6589fffd.png)
It's giving me an error. Ill reload game and try again

**Comment by Codemned** [comment]
Dunno never had issues myself, Is your xivlauncher up to date?

**Comment by Codemned** [comment]
Anyway 1 gauss and 1 rico per heatblast yes or no?

**Comment by sauronshotdogs** [comment]
Seems a restart was needed, it now works. 

I don't think its possible to put in 2 per heatblast. You could try making that an additional option, of not too much work. But if it is, then just stick with 1 per

**Comment by sauronshotdogs** [comment]
Alright, tried it out, and it works perfectly!

**Comment by Codemned** [comment]
Well wtf am i trying to fix then?

**Comment by sauronshotdogs** [comment]
I think Aki might have fixed it, but not deployed it yet. The devbuild has given me options I did not have before

**Comment by Codemned** [comment]
Wait i'll make two different versions and you can tell me which one is better.
No no no this is all me dude.

> I think Aki might have fixed it, but not deployed it yet. The devbuild has given me options I did not have before
No no no this is all me dude. I'll have my due credit thank you very much!

**Comment by sauronshotdogs** [comment]
Thank you very much then. It does work now. Seems it just wasn't deployed.

#55 and #57 were added/changed, and I would like to make a note on it. 
Again, it works perfectly. I would, however, ask if you could move the priorities around on #55, so it prios Drill, instead of Air Anchor

**Comment by Codemned** [comment]
I thought the opener was anchor then drill?

**Comment by sauronshotdogs** [comment]
Opposite. Again, that might have been me not explaining stuff correctly

**Comment by sauronshotdogs** [comment]
I really do appreciate the work each of you do, and I am very sorry for being so shit at explaining my requests properly.

**Comment by Codemned** [comment]
No, I looked it up on The Balance discord since I don't Machinist.

**Comment by Codemned** [comment]
I'll fix it and push then Aki can release when he feels like it.

**Comment by sauronshotdogs** [comment]
Huh, I again confirmed the fact that I am an idiot. I have always used drill first. But as it turns out, it doesn't really matter, as they have the same potency. You can feel free to disregard, as what you originally did, was correct.

**Comment by Codemned** [comment]
OK I'll leave it and you can play with the dev build till Aki pushes a release, Have a great day!

**Comment by sauronshotdogs** [comment]
You too, and thanks!
