### ISSUE TITLE
[MCH] Feature: an identical #55, but when it won't trigger at all, unless Reassemble is active

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/MyDalamudPlugins#25]
An identical feature as 55, where is adds drill/air onto main combo when reassemble is active.

The current one adds it if reassemble is active OR on cooldown. I would like this to ONLY activate if Reassemble is active

**Comment by Codemned** [comment]
I'll look into that.

**Comment by sauronshotdogs** [comment]
Thanks!

**Comment by Codemned** [comment]
I need to you clarify for me, What exactly do you want it to do?

**Comment by Codemned** [comment]
I have a preliminary fix but I can't test Machinist at a higher level.

**Comment by sauronshotdogs** [comment]
Mine is 80, but that will work for this request

**Comment by sauronshotdogs** [comment]
It works great, thanks!

**Comment by sauronshotdogs** [comment]
Would it be possible to make this work synched?

Before 76 Air Anchor is Hot Shot.

Same goes for #55

**Comment by Codemned** [comment]
![mch](https://user-images.githubusercontent.com/95727084/146009410-38841279-dc4b-472b-89b3-ade4bb42bad6.png)
#54??

**Comment by sauronshotdogs** [comment]
Dude, I am just retarded when it comes to numbers today. I ofc mean 55, sorry.

I have referred to the wrong number each and every single time today.

To avoid any confusion, I am referring to the Drill/Air Anchor feature.

**Comment by Codemned** [comment]
I've written a fix for #56 but #55 is working as intended?

**Comment by sauronshotdogs** [comment]
Yeah, again I managed to fuck up numbers. Thanks a lot for managing to navigate through my requests.

**Comment by Codemned** [comment]
So just the issue with #56 then?

**Comment by sauronshotdogs** [comment]
Yes. Thanks a bunch!

**Comment by Codemned** [comment]
I've pushed the fix wait for update to Release.

**Comment by sauronshotdogs** [comment]
Awesome, thanks again!
