### ISSUE TITLE
AST #5 Feature Bug

### ISSUE THREAD

**Issue by Sky-Lochagos** [Nik-Potokar/MyDalamudPlugins#26]
After the first Fall Malefic, it properly swaps to Combust III, then straight to Combust II and doesn't swap again until Combust III wears off and then it swaps back to Combust III. It never swaps back to Fall Malefic.

Doesn't allow attacking after applying the DoT.

Fall Malefic -> Combust III -> Combust II ("Cannot use yet." error) -> Combust III

**Comment by Codemned** [comment]
Fixed for next update.
