### ISSUE TITLE
AST DPS Feature

### ISSUE THREAD

**Issue by nemorisailor** [Nik-Potokar/MyDalamudPlugins#27]
Malefic doesn't seem to get replaced with Combust at all and the feature seem to not do anything

**Comment by Codemned** [comment]
Missing argument in the code, it's been fixed for next update.

**Comment by Sky-Lochagos** [comment]
Same issue since last update.
Edit: Affects white mage as well, no skill swap.

**Comment by Nik-Potokar** [comment]
Fix should be live now please let me know if its functions correctly  (Make sure to drag Fall Malefic/Glare3 on hotbar)

**Comment by Sky-Lochagos** [comment]
Works for AST, WHM it swaps to Aero II instead of Dia at level 80, not 90 yet to test fully.

**Comment by Nik-Potokar** [comment]
Ahh yes i mistyped the number 
Pushing a fix for it now
ver:1.6.50

Let me know if its working.

Thank you

**Comment by Sky-Lochagos** [comment]
Works!

**Comment by Nik-Potokar** [comment]
Thanks for getting back to me^^

Let me know if you get any other issues and il fix them ASAP!

Thank you again
