### ISSUE TITLE
RPR add buffer to ReaperEnshroudCommunioFeature to prevent accidental activation of Communio

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/MyDalamudPlugins#28]
Suggestion to add 3 second buffer on Enshroud, so you prevent accidentally hitting Communio and ending burst early.

**Comment by Codemned** [comment]
You want #88 to have a delay when switching its button? So you don't accidentaly blow communio while mashing the button right?
![bild](https://user-images.githubusercontent.com/95727084/146396526-59c35c1f-874c-4cb5-87ee-aa9c35cf9cff.png)

**Comment by Codemned** [comment]
It's probably the only thing it could be (Don't have Reaper leveled) from what I've been able to deduce and a fix will be comming.

**Comment by sauronshotdogs** [comment]
That is correct. a Delay of 3 secs is fine

**Comment by Codemned** [comment]
I pushed a fix now someone needs to test it.

**Comment by sauronshotdogs** [comment]
Will do asap

Works perfectly, thanks for the quick work!
