### ISSUE TITLE
[RPR] Death's Design & Combos

### ISSUE THREAD

**Issue by rushtothesun** [Nik-Potokar/MyDalamudPlugins#29]
Hi I've noticed, especially between packs of monsters, that if I'm in the middle of a combo move the combo chain is prioritized over the Death's Design buff (Shadow of Death/Whorl of Death). This leads to losing potency on one or more abilities. Since applying Death's Design does not interrupt our combo chains I think a check needs to be added where lastComboMove is used.

**Comment by Nik-Potokar** [comment]
Fix coming for that later today 

Thanks for testing

**Comment by sauronshotdogs** [comment]
Can't wait!
