### ISSUE TITLE
[BLM] All in one AoE repeats Thunder IV twice

### ISSUE THREAD

**Issue by rushtothesun** [Nik-Potokar/MyDalamudPlugins#30]
Thunder IV has a short animation time once it is casted before the actual effect is applied. During this animation time you can queue up another spell and because the effect hasn't applied yet that next spell will be Thunder IV again instead of Fire2/HighFire2

**Comment by sauronshotdogs** [comment]
That is being worked on, it will do T4 twice if you spam it. It you slow down when T4 is being cast, you'll notice it won't double. Quoting Aki: 

> So the double thunder it's cause of the way blm dot is. Since it's not instant you have to delay your cast for 0.3sec since if you spam the button it will cast another thunder
I don't have a workaround for that yet
Since it's just the way the skill works (other dots apply instantly)
So current solution is ether wait a split sec or you have to manually use thunder and I remove it from one button (or another workaround)

**Comment by rushtothesun** [comment]
> That is being worked on, it will do T4 twice if you spam it. It you slow down when T4 is being cast, you'll notice it won't double

I think I've fixed it. My coding knowledge is limited so I'm sure there's a better way but for the Thunder IV logic I did:

`if (lastComboMove == BLM.Thunder4)
                        {                            
                        }else
                        {
                            return BLM.Thunder4;
                        }`

And then for the next fire line we need to add 

`|| (gauge.InUmbralIce && gauge.UmbralHearts == 3 && lastComboMove == BLM.Thunder4)`

Otherwise HighBlizzard2 will be used right after ThunderIV

**Comment by rushtothesun** [comment]
Also there's another issue with the current Thunder IV logic.  We have checks in the Fire Phase that rely on thunder4Debuff being true. If the thunder4Debuff is false then it reverts to using HighBlizzardII. There is a period after you have casted Thunder IV but before you cast HighFireII where if you for example need to move for a mechanic or multiple mechanics in a row, your Thunder IV will expire during the the Fire phase which will cause the Fire Phase to abruptly go back to HighBlizzardII. 

From what I understand, it is beneficial to cast Thunder IV at any time during the Fire Phase if it drops. So I think logic needs to be added to the current Thunder IV  section where if you're InAstralFire and the debuff is not active then cast Thunder IV.  If this is done you'll also need to add an or statement with `lastComboMove == BLM.Thunder4`  to the other 2 if statements for the fire phase.

Also for line 247:  

`if (gauge.InUmbralIce && gauge.UmbralHearts == 0)`

I think UmbralHearts <=2 would be a better option here to prevent a Blizzard loop in the event of an accident. Like if you were to ThunderIV, HighFire2, HighFire2, and then you pressed Blizzard III for some reason the AoE button would be stuck.

Edit: I'll just attach what I've done so far
[BLM.zip](https://github.com/Nik-Potokar/MyDalamudPlugins/files/7733583/BLM.zip)
.

**Comment by Nik-Potokar** [comment]
Fix coming later today and thank you for already doing some work for me!

Also there will be an update with low level version coming today as well

Thank you again for all the details

**Comment by Nik-Potokar** [comment]
Should be fixed and also added low level AoE combo

**Comment by rushtothesun** [comment]
> Should be fixed and also added low level AoE combo

I forgot to mention that Thunder 3 in the BlackEnochianFeature combo has the same double use issue. So the same fix in the aoe combo will need to be used in the BlackEnochianFeature  combo.
