### ISSUE TITLE
[MCH] Scattergun additions

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/MyDalamudPlugins#32]
At 82, Spread shot turns into Scattershot. This breaks the feature that would turn it into Auto Crossbow when Overheated.

In addition to this, adding Bioblaster to the beginning of this button, would fit right into the AOE rotation. 

Thanks

**Comment by sauronshotdogs** [comment]
Adding Bio Blaster to this would be nice as well, preferably before it

**Comment by sauronshotdogs** [comment]
There is also no way to make scattershot turn into auto crossbow atm

**Comment by Codemned** [comment]
Added needs testing.
I did nothing with BioBlaster because I don't fully understand it yet.

**Comment by sauronshotdogs** [comment]
Thanks, Ill pull and test right away. It's an AOE dot, if that helps anything. Shares a cd with Drill,

**Comment by sauronshotdogs** [comment]
Works perfectly. Lemme know when you add Bioblaster.

Thanks a bunch !

**Comment by Codemned** [comment]
Bioblaster has been added.

**Comment by sauronshotdogs** [comment]
Works perfectly, thanks dude! Tested at various lvls also, and ran into no issues
