### ISSUE TITLE
[MCH] Add Chain Saw to Drill/Air feature 

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/MyDalamudPlugins#34]
Back at it again with another Machinist request.

In the opener, Chain Saw appears last, right between  wildfire and hypercharge. It would probably to be optimal to add it to the drill/air feature at the bottom of the queue, since you fire those off off first anyways.

can be sourced from https://github.com/Grammernatzi/XIVComboPluginExpandedest without credit

**Comment by Codemned** [comment]
Added needs testing.
I miss understood this request and I've added this to "Drill/Air/Chain Saw Feature On Main Combo"

Air/drill will be updated to Grammernatzi's implementation.

**Comment by sauronshotdogs** [comment]
Thanks! You'd probably want to have chainsaw on those anyways, adding it onto the alt version wouldn't hurt I think.

Have you found a fix for #57 and #59 not working right with the extra charge of Reassembly you get at 84?

**Comment by Codemned** [comment]
Grammarnatzi's Solution added.
Can you take a screenshot of #57 and #59 I'm in a massive queue and can't check anything right now.
But I did fix Reassembly for AlternateMainCombo this morning.

**Comment by Codemned** [comment]
Looked at the code and there shouldn't be any issues with Reassembly.

**Comment by sauronshotdogs** [comment]
![image](https://user-images.githubusercontent.com/95890035/146594285-e42d3599-4126-4afe-8fe6-a87868a54b7d.png)

**Comment by sauronshotdogs** [comment]
> Looked at the code and there shouldn't be any issues with Reassembly.

It seems to think any cooldown, means it has no charges left. A guess would be tracking the charges instead of it being on CD or not. I do not code, so that might just be impossible, or just stupid

**Comment by Codemned** [comment]
Pushed a fix for that this morning test and confirm?

**Comment by sauronshotdogs** [comment]
I use #57, but I will test #59

**Comment by sauronshotdogs** [comment]
also, this is a thing
![image](https://user-images.githubusercontent.com/95890035/146594764-cd2e1f5a-32fd-401a-9805-4fb3c23a273e.png)

**Comment by Codemned** [comment]
Already fixed bad copy pasta!
It will compile now.
Or it would have if I actually pused the fix sorry...

**Comment by sauronshotdogs** [comment]
haha, I was thinking my vs was broken or something. No worries

**Comment by sauronshotdogs** [comment]
Alright, the 1 button oGCD (Hot shot, drill, air anchor, chain saw) works. Lovely!

**Comment by sauronshotdogs** [comment]
Which program do you use to record those gifs?

**Comment by Codemned** [comment]
Screentogif https://www.screentogif.com/

**Comment by sauronshotdogs** [comment]
Thanks, I will make a gif of the reassembly issue then

**Comment by sauronshotdogs** [comment]
![Animation](https://user-images.githubusercontent.com/95890035/146596935-f19f83d7-b56a-4114-b577-6c179ebb5248.gif)
This is the alternate. It only triggers after 2nd use of reassembly

**Comment by sauronshotdogs** [comment]
![Main](https://user-images.githubusercontent.com/95890035/146597140-e82c2892-bcc0-4207-ba2e-acdc2130df25.gif)
this is main. You'll see that after using main combo once, and thus using air anchor, it doesn't care about the remaining charge of reassembly

**Comment by Codemned** [comment]
I'll try to find a solution but I haven't found anyway to track charges on skills.

**Comment by sauronshotdogs** [comment]
While I have you, would you kindly add these 2 features from Grammarnatzi? It's for reaper

![image](https://user-images.githubusercontent.com/95890035/146598474-923048a5-05ca-47e4-b69f-778bbc405ab4.png)

**Comment by Codemned** [comment]
Main should be working fine it's modeled after this opener:
![mch_ew_opener](https://user-images.githubusercontent.com/95727084/146598554-198c8871-2ca8-4b39-a54d-8d0fd69be9ad.png)
 Try the full opener and tell me if it doesn't hold off on the Chain Saw untill you use your second charge of Reassemble.

**Comment by Codemned** [comment]
I'll look into grammars stuff later.

**Comment by sauronshotdogs** [comment]
> Main should be working fine it's modeled after this opener: ![mch_ew_opener](https://user-images.githubusercontent.com/95727084/146598554-198c8871-2ca8-4b39-a54d-8d0fd69be9ad.png) Try the full opener and tell me if it doesn't hold off on the Chain Saw untill you use your second charge of Reassemble.

Oh I see. Drill is allowed, but AA and CS isn't. That is very nice work dude! Even though I asked you to add Wildfire into the main Hypercharge combo, I guess either removing it again, or changing the order would be the most optimal

**Comment by Codemned** [comment]
Make it pop wildfire before hypercharge yes?
Can you pull and test a change to Alternate?

**Comment by sauronshotdogs** [comment]
Sure. What is the change?

**Comment by Codemned** [comment]
See if it works on one charge?

**Comment by sauronshotdogs** [comment]
see if what works?

**Comment by Codemned** [comment]
> ![Animation](https://user-images.githubusercontent.com/95890035/146596935-f19f83d7-b56a-4114-b577-6c179ebb5248.gif) This is the alternate. It only triggers after 2nd use of reassembly

**Comment by sauronshotdogs** [comment]
gotcha

**Comment by sauronshotdogs** [comment]
Works on 1st charge, doesn't know about Chain Saw though

**Comment by Codemned** [comment]
It's not for 90+ so I can write it off as fixed?

**Comment by sauronshotdogs** [comment]
Sure. It doesn't require reassembly for activation, if reassembly only has 1 stack left

**Comment by Codemned** [comment]
Ok just so I'm understanding this 100% before it wouldn't insert Airacnhor if you still had 1 charge left of reassemble now it will insert it as soon as you spend your first charge?

**Comment by sauronshotdogs** [comment]
![altnew](https://user-images.githubusercontent.com/95890035/146600885-070a15ab-9cbb-49a7-bd02-3b9071300520.gif)

**Comment by Codemned** [comment]
Ok good, can you test synced below 84 and cofirm it's still working?

**Comment by sauronshotdogs** [comment]
Will do. did you time it to the cd? When reassembly hits 50 on cd, drill will need another activation of reassembly to fire. (This is what I requested, albeit the timer could be a bit shorter)

**Comment by Codemned** [comment]
Yes the whole idea with Alternate is to not have to think about the Air/hotshot/drill cooldown.
I pushed another test for it could you pull and try that? Above and below 84?

**Comment by sauronshotdogs** [comment]
Need me to test the previous pull below 84 still?

**Comment by Codemned** [comment]
No

**Comment by sauronshotdogs** [comment]
remember to push

**Comment by Codemned** [comment]
Just see if it'll insert Drill/AirAnchor/Hotshot when Reaaemble is on less than 2 charges.

**Comment by Codemned** [comment]
Ahh shit it'll break when your synced below 84.

**Comment by sauronshotdogs** [comment]
![altnewnew](https://user-images.githubusercontent.com/95890035/146601709-382e9217-9a0f-4165-86a3-685073274f9a.gif)
Synced around 60

The one marked with 1 is obviously the one to look for. Seems it works

**Comment by Codemned** [comment]
Yeah but if you wait for Reassemble to come back off cooldown it's still going to insert Hotshot/drill.

**Comment by sauronshotdogs** [comment]
So you want me to be synced below 84, and see if after reassembly comes off cd, if anything will happen to main combo?

**Comment by Codemned** [comment]
You don't need to I aldready know it won't remove drill/air from main combo.

**Comment by Codemned** [comment]
Alternate is broken Main is working fine, i'll probably need to make two seperate alternate versions 1 for 84 or higher and one for 83 or lower.

**Comment by sauronshotdogs** [comment]
Yeah, it will enable drill, but it won't disappear when reassembly buff disappears

**Comment by Codemned** [comment]
Yes broken, can't fix since there is no way to track stacks, pre 84 and you use reassemble it will think you spent 2 charges when you only have 1 and set the cooldown to 110 seconds instead of 55. I'll keep working on it. Thanks for testing.

**Comment by sauronshotdogs** [comment]
Since main is following the opener, wouldn't that just be the standard to use at 90, and just the existing alt feature for 84 and below?

Thanks for working on, and fixing these!

**Comment by Codemned** [comment]
Yeah but Alternate is chill AF

**Comment by sauronshotdogs** [comment]
> Yeah but Alternate is chill AF

I agree, it is nice to not have to worry about it.

**Comment by sauronshotdogs** [comment]
Ill make a new issue about doing something optimal about wildfire.
