### ISSUE TITLE
[MCH] Wildfire optimal use

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/MyDalamudPlugins#35]
Wildfire placement in combo in regards to optimal opener

![image](https://user-images.githubusercontent.com/95890035/146603363-f7cbc229-87ea-4b5c-881e-60a40f2cd3d7.png)

**Comment by Codemned** [comment]
I've changed Single Button Heat Blast to use Wildfire before hypercharge, IF Wildfire is off cooldown but I'll need to test it myself before I commit more changes.
It's in the works basicly.

**Comment by sauronshotdogs** [comment]
I will try it out and report back

**Comment by Codemned** [comment]
Updated, Single Button Heat Blast should be solid now.

**Comment by sauronshotdogs** [comment]
Works great! Did you remove wildfire from single button heatblast on main combo option?

**Comment by Codemned** [comment]
I'll fix that for a push later.
