### ISSUE TITLE
[MCH] Alternate Drill / Air Feather on Main Combo issue

### ISSUE THREAD

**Issue by hokeenthong** [Nik-Potokar/MyDalamudPlugins#37]
Hi,

Noticed that Chain Saw skill is being added to this combo. However, when 2 skills (Air Anchor and Drill) are on cool down, the button will  change to Hot Shot and cannot be clicked.

**Comment by hokeenthong** [comment]
Sorry, just notice another issue. For the feature "Drill/Air/Chain Saw Feature on Main Combo", if all 3 skills are on cool down and reassemble is pressed, the button will default on one of the 3 skills (Drill/Air/Chain Saw) on cooldown and the combo will not work. It will go back to normal, if the reassemble buff disappears. 

No doubt that reassemble should always be used with one of the 3 skills but I am worried that reassemble can be pressed accidentally.   

Thanks.

**Comment by Codemned** [comment]
Chain Saw wasn't added to Alternate Drill, The HotShot issue will be fixed.
Drill/Air/Chain issue will be fixed as well.
Thanks for reporting these issues.

**Comment by sauronshotdogs** [comment]
d48cbddb0893f0e54f9427aec92e0bd6fedac6dd

Alternate seems to be fixed at 90 at least. if drill and AA is on cd, and reassemble is pressed, Chain Saw will show.

I am still experiencing the issue on main where, if all 3 are on cd, and reassembled is pressed, it will put one of them into main combo, making it unusable.

**Comment by Codemned** [comment]
Looking at the code after some much needed sleep, I've removed my spagheti code and fixed it properly.
Test it to confirm if you get the chance, I'll be in the queue for a while...

**Comment by sauronshotdogs** [comment]
No worries dude, I was thinking how the hell you were fixing shit on here at all hours of the day. Ill report back right away

**Comment by sauronshotdogs** [comment]
Main looks fixed. THanks!

If you have the time, energy and want, I'd absolutely love it, would you look at https://github.com/Nik-Potokar/MyDalamudPlugins/issues/29

**Comment by Codemned** [comment]
Good thanks for testing, Wait for update to release.

**Comment by Codemned** [comment]
#29 ... Is a tough one. It's being looked into is all I can say atm.

**Comment by sauronshotdogs** [comment]
Thanks for the info!

**Comment by hokeenthong** [comment]
Thank you for fixing this.
