### ISSUE TITLE
Warrior Fellcleave/IB feature bug

### ISSUE THREAD

**Issue by Codemned** [Nik-Potokar/MyDalamudPlugins#9]
The Warrior Fellcleave/IB feature doesn't always use Inner Beast before overcapping and getting stuck with Fellcleave when synced between level 35-53.

It never shows the Inner Beast icon in the hotbar only Fellcleave when trying to automatically not overcap the warrior gauge.

It's easy to reproduce and test the bug by joining cutter's cry with Unrestricted and level synced party options enabled.

This was tested on Version 1.5.0

**Comment by Nik-Potokar** [comment]
Just tested a fix for it seems to be working now
Fixed by adding a level check
The Fix update should be live now

Thanks again for helping me finding issues <3

**Comment by Codemned** [comment]
It still breaks on 1.5.1

I did see it insert inner beast into the main rotation correctly sometimes but it'll still try to use fellcleave 9 out of 10 times breaking the feature.

edit: If it's going to overcap after heavy swing inner beast correctly gets used but if it's at any other point during the rotation it breaks as far as i can tell.

**Comment by Nik-Potokar** [comment]
Oh yeah i see i forgot something
Now it should be fine

**Comment by Codemned** [comment]
I can't test that right now but overcap feature won't trigger on the aoe combo.

**Comment by Nik-Potokar** [comment]
Also fixed/reworked AoE overcap as requested

**Comment by Codemned** [comment]
I have been unable to break the feature since 1.5.2 so that's definitely fixed and on the AoE overcap thing that was totally me being a dum dum :P

Thanks for your quick work!
